POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudGp1bnR1IiwiaWQiOiI1YmVjMTZmZGFmZGJlNzFkYzQ4YTRhMTciLCJpYXQiOjE1NDIzNzA2ODZ9.WxgGmup3y03XawAMWPNy4qJo6RijjqnpJm1jdUkUjlA

{
  "content": "Toinen note",
  "important": false
}